# Build iOS and Android examples for @evervault/react-native
name: React Native Workflow
on:
  push:
    paths:
      - "examples/expo/**"
      - "packages/react-native-v2/**"
      - ".github/**"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
jobs:
  build_ios:
    name: Build iOS Examples
    # We can use smaller runners when we move to React Native >0.80 in the expo project.
    runs-on: macos-15-xlarge
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          # xcode-version: latest-stable
          # Temporarily use V16.4 while Github rolls out v26 update
          xcode-version: 16.4
      - name: Checkout Repo
        uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Build dependencies
        run: pnpm build
      - name: Prebuild iOS
        run: pnpm examples:expo prebuild
      - name: Build iOS
        working-directory: examples/expo/ios
        run: |
          # Set pipefail so we capture errors correctly.
          set -o pipefail
          xcodebuild build -workspace "evervaultexpoexample.xcworkspace" -scheme "evervaultexpoexample" -configuration Release -sdk iphonesimulator | xcpretty

  build_android:
    name: Build Android Examples
    # We can use smaller runners when we move to React Native >0.80 in the expo project.
    runs-on: ev-runner-x-large
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Build dependencies
        run: pnpm build
      - name: Prebuild Android
        run: pnpm examples:expo prebuild
      - name: Build Android
        working-directory: examples/expo/android
        run: ./gradlew assembleRelease --parallel --build-cache
