name: Update Screenshots
on:
  workflow_dispatch:
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  update-screenshots:
    uses: ./.github/workflows/e2e-test.yml
    with:
      vite-evervault-js-url: "https://js.evervault.com/v2"
      vite-keys-url: "https://keys.evervault.com"
      vite-api-url: "https://api.evervault.com"
      run-code-coverage-checks: false
      update-screenshots: true
    secrets: inherit
